title: Civic Resilience

# If your site is at username.github.io/infoportal use this:
baseurl: "/infoportal"
# If your site is at username.github.io (no repo path), set: baseurl: ""

collections:
  preparedness:
    output: true
    permalink: /preparedness/:name/
  secure:
    output: true
    permalink: /secure/:name/
topics:
    output: true
    permalink: /topics/:name

defaults:
# Preparedness collection docs get the "guide" layout by default
  - scope:
      path: ""              # Anywhere in the repo
      type: preparedness    # applies only to _preparedness/*
    values:
      layout: guide
      nav_section: preparedness

# Secure collection docs
  - scope:
      path: ""
      type: secure
    values:
      layout: guide
      nav_section: secure

# Topics collection
  - scope:
      path: "guide"
      type: topics
    values:
      layout: guide
      nav_section: topics
